AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Win-Win development workflows, supporting both ECS/EKS Container and Lambda Functions 🎯🚀🌥
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CrawlFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Crawl:
          Type: Api
          Properties:
            Path: /crawl
            Method: get
    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: ./docker
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CrawlApi:
    Description: "API Gateway endpoint URL for Prod stage for Crawl function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/crawl/"
  CrawlFunction:
    Description: "Crawl Lambda Function ARN"
    Value: !GetAtt CrawlFunction.Arn
  CrawlFunctionIamRole:
    Description: "Implicit IAM Role created for Crawl function"
    Value: !GetAtt CrawlFunctionRole.Arn
